name = "aiken-lang/perma-lock"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/perma-lock'"

[repository]
user = "aiken-lang"
project = "perma-lock"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"