name = "dripdropz/perma-lock"
version = "1.1.4"
license = "GPL-3.0-or-later"
description = "Perma Lock Contract For Dripdropz"

[repository]
user = "dripdropz"
project = "perma-lock"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.9"
source = "github"