name = "Dripdropz/perma-lock"
version = "1.1.1"
license = "GPL-3.0-or-later"
description = "Aiken contracts for project 'Dripdropz/perma-lock'"

[repository]
user = "aiken-lang"
project = "perma-lock"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.6"
source = "github"