name = "Dripdropz/perma-lock"
version = "1.1.0"
license = "GPL-3.0"
description = "Aiken contracts for project 'Dripdropz/perma-lock'"

[repository]
user = "aiken-lang"
project = "perma-lock"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"